/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#include <stdint.h>
#include "bg_gattdb_def.h"

#ifdef __GNUC__
#define GATT_HEADER(F) F __attribute__ ((section (".gatt_header"))) 
#define GATT_DATA(F) F __attribute__ ((section (".gatt_data"))) 
#else
#ifdef __ICCARM__
#define GATT_HEADER(F) _Pragma("location=\".gatt_header\"") F 
#define GATT_DATA(F) _Pragma("location=\".gatt_data\"") F 
#else
#define GATT_HEADER(F) F 
#define GATT_DATA(F) F 
#endif
#endif

GATT_DATA(const uint16_t bg_gattdb_uuidtable_16_map [])=
{
    0x2800,
    0x2801,
    0x2803,
    0x1800,
    0x2a00,
    0x2a01,
    0x180a,
    0x2a29,
    0x2a24,
    0x2a23,
    0x1803,
    0x2a06,
    0x1802,
    0x1804,
    0x2a07,
    0x2902,
};

GATT_DATA(const uint8_t bg_gattdb_uuidtable_128_map [])=
{
0x0f, 0x40, 0x7f, 0x5c, 0x7a, 0x2e, 0x41, 0xa7, 0x5a, 0x4f, 0xa9, 0x51, 0x65, 0xff, 0xc7, 0x6c, 
0xb9, 0x80, 0xa0, 0x5a, 0xeb, 0x19, 0xbf, 0xb9, 0x42, 0x44, 0xa5, 0x51, 0xf1, 0x53, 0x68, 0x5d, 
0xeb, 0x28, 0xc0, 0xb8, 0xa1, 0xee, 0x37, 0x82, 0x02, 0x46, 0x75, 0xe7, 0x2e, 0x50, 0x02, 0x8f, 
0x9d, 0xb9, 0xcb, 0xc0, 0xf4, 0x4b, 0xcc, 0x8d, 0x05, 0x4d, 0xa8, 0x95, 0x67, 0x60, 0x74, 0x9e, 
0x4d, 0x54, 0x5a, 0xf5, 0xd2, 0x31, 0x9a, 0x96, 0x6e, 0x4a, 0x81, 0xd3, 0x82, 0xc2, 0x58, 0x5b, 
0x88, 0xf9, 0xa4, 0xec, 0x49, 0x24, 0x87, 0xb3, 0xb0, 0x4d, 0x49, 0xbb, 0x4c, 0x2f, 0x1a, 0x0b, 
0x69, 0xe5, 0xb4, 0x20, 0xa1, 0x32, 0x45, 0x89, 0xc2, 0x42, 0x89, 0x63, 0x07, 0x40, 0x21, 0x56, 
0x75, 0xfc, 0x15, 0x69, 0xcf, 0xe1, 0xc8, 0x97, 0x2b, 0x4a, 0x9a, 0xc5, 0x3f, 0x42, 0xe6, 0x00, 
0x37, 0xe9, 0x5e, 0x87, 0xa3, 0xa3, 0xa5, 0x85, 0x45, 0x41, 0xd5, 0x94, 0x1b, 0xf2, 0x2c, 0x40, 
0x3f, 0x62, 0x0b, 0x90, 0x17, 0xb8, 0xbb, 0xae, 0x52, 0x4a, 0xca, 0x3b, 0x32, 0xbf, 0xc7, 0xf8, 
};




struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_47_data = {
	.len=1,
	.data={0x09,}
};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_47 ) = {
	.properties=0x1a,
	.index=11,
	.max_len=20,
	.data_varlen=&bg_gattdb_attribute_field_47_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_46 ) = {
	.len=19,
	.data={0x1a,0x30,0x00,0x3f,0x62,0x0b,0x90,0x17,0xb8,0xbb,0xae,0x52,0x4a,0xca,0x3b,0x32,0xbf,0xc7,0xf8,}
};
uint8_t bg_gattdb_attribute_field_44_data[3]={0x08,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_44 ) = {
	.properties=0x2a,
	.index=10,
	.max_len=3,
	.data=bg_gattdb_attribute_field_44_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_43 ) = {
	.len=19,
	.data={0x2a,0x2d,0x00,0x37,0xe9,0x5e,0x87,0xa3,0xa3,0xa5,0x85,0x45,0x41,0xd5,0x94,0x1b,0xf2,0x2c,0x40,}
};
uint8_t bg_gattdb_attribute_field_41_data[3]={0x07,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_41 ) = {
	.properties=0x2a,
	.index=9,
	.max_len=3,
	.data=bg_gattdb_attribute_field_41_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_40 ) = {
	.len=19,
	.data={0x2a,0x2a,0x00,0x75,0xfc,0x15,0x69,0xcf,0xe1,0xc8,0x97,0x2b,0x4a,0x9a,0xc5,0x3f,0x42,0xe6,0x00,}
};
uint8_t bg_gattdb_attribute_field_38_data[3]={0x06,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_38 ) = {
	.properties=0x2a,
	.index=8,
	.max_len=3,
	.data=bg_gattdb_attribute_field_38_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_37 ) = {
	.len=19,
	.data={0x2a,0x27,0x00,0x69,0xe5,0xb4,0x20,0xa1,0x32,0x45,0x89,0xc2,0x42,0x89,0x63,0x07,0x40,0x21,0x56,}
};
uint8_t bg_gattdb_attribute_field_35_data[3]={0x05,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_35 ) = {
	.properties=0x2a,
	.index=7,
	.max_len=3,
	.data=bg_gattdb_attribute_field_35_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_34 ) = {
	.len=19,
	.data={0x2a,0x24,0x00,0x88,0xf9,0xa4,0xec,0x49,0x24,0x87,0xb3,0xb0,0x4d,0x49,0xbb,0x4c,0x2f,0x1a,0x0b,}
};
uint8_t bg_gattdb_attribute_field_32_data[3]={0x04,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_32 ) = {
	.properties=0x2a,
	.index=6,
	.max_len=3,
	.data=bg_gattdb_attribute_field_32_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_31 ) = {
	.len=19,
	.data={0x2a,0x21,0x00,0x4d,0x54,0x5a,0xf5,0xd2,0x31,0x9a,0x96,0x6e,0x4a,0x81,0xd3,0x82,0xc2,0x58,0x5b,}
};
uint8_t bg_gattdb_attribute_field_29_data[3]={0x03,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_29 ) = {
	.properties=0x2a,
	.index=5,
	.max_len=3,
	.data=bg_gattdb_attribute_field_29_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_28 ) = {
	.len=19,
	.data={0x2a,0x1e,0x00,0x9d,0xb9,0xcb,0xc0,0xf4,0x4b,0xcc,0x8d,0x05,0x4d,0xa8,0x95,0x67,0x60,0x74,0x9e,}
};
uint8_t bg_gattdb_attribute_field_26_data[3]={0x02,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_26 ) = {
	.properties=0x2a,
	.index=4,
	.max_len=3,
	.data=bg_gattdb_attribute_field_26_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_25 ) = {
	.len=19,
	.data={0x2a,0x1b,0x00,0xeb,0x28,0xc0,0xb8,0xa1,0xee,0x37,0x82,0x02,0x46,0x75,0xe7,0x2e,0x50,0x02,0x8f,}
};
uint8_t bg_gattdb_attribute_field_23_data[3]={0x01,0x00,0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_23 ) = {
	.properties=0x2a,
	.index=3,
	.max_len=3,
	.data=bg_gattdb_attribute_field_23_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_22 ) = {
	.len=19,
	.data={0x2a,0x18,0x00,0xb9,0x80,0xa0,0x5a,0xeb,0x19,0xbf,0xb9,0x42,0x44,0xa5,0x51,0xf1,0x53,0x68,0x5d,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_21 ) = {
	.len=16,
	.data={0x0f,0x40,0x7f,0x5c,0x7a,0x2e,0x41,0xa7,0x5a,0x4f,0xa9,0x51,0x65,0xff,0xc7,0x6c,}
};
uint8_t bg_gattdb_attribute_field_20_data[1]={0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_20 ) = {
	.properties=0x02,
	.index=2,
	.max_len=1,
	.data=bg_gattdb_attribute_field_20_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_19 ) = {
	.len=5,
	.data={0x02,0x15,0x00,0x07,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_18 ) = {
	.len=2,
	.data={0x04,0x18,}
};
uint8_t bg_gattdb_attribute_field_17_data[1]={0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_17 ) = {
	.properties=0x04,
	.index=1,
	.max_len=1,
	.data=bg_gattdb_attribute_field_17_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_16 ) = {
	.len=5,
	.data={0x04,0x12,0x00,0x06,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_15 ) = {
	.len=2,
	.data={0x02,0x18,}
};
uint8_t bg_gattdb_attribute_field_14_data[1]={0x00,};
GATT_DATA(const struct bg_gattdb_attribute_chrvalue	bg_gattdb_attribute_field_14 ) = {
	.properties=0x0a,
	.index=0,
	.max_len=1,
	.data=bg_gattdb_attribute_field_14_data,
};

GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_13 ) = {
	.len=5,
	.data={0x0a,0x0f,0x00,0x06,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_12 ) = {
	.len=2,
	.data={0x03,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_11 ) = {
	.len=6,
	.data={0x00,0x07,0x80,0x00,0x00,0x47,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_10 ) = {
	.len=5,
	.data={0x02,0x0c,0x00,0x23,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_9 ) = {
	.len=11,
	.data={0x6b,0x44,0x72,0x69,0x76,0x65,0x20,0x76,0x31,0x2e,0x30,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_8 ) = {
	.len=5,
	.data={0x02,0x0a,0x00,0x24,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_7 ) = {
	.len=11,
	.data={0x54,0x68,0x6f,0x6d,0x61,0x73,0x20,0x43,0x6f,0x72,0x70,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_6 ) = {
	.len=5,
	.data={0x02,0x08,0x00,0x29,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_5 ) = {
	.len=2,
	.data={0x0a,0x18,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_4 ) = {
	.len=2,
	.data={0x09,0x60,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_3 ) = {
	.len=5,
	.data={0x02,0x05,0x00,0x01,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_2 ) = {
	.len=6,
	.data={0x6b,0x44,0x72,0x69,0x76,0x65,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_1 ) = {
	.len=5,
	.data={0x02,0x03,0x00,0x00,0x2a,}
};
GATT_DATA(const struct bg_gattdb_buffer_with_len	bg_gattdb_attribute_field_0 ) = {
	.len=2,
	.data={0x00,0x18,}
};
GATT_DATA(const struct bg_gattdb_attribute bg_gattdb_attributes_map[])={
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_0},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_1},
    {.uuid=0x0004,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_2},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_3},
    {.uuid=0x0005,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_4},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_5},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_6},
    {.uuid=0x0007,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_7},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_8},
    {.uuid=0x0008,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_9},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_10},
    {.uuid=0x0009,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_11},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_12},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_13},
    {.uuid=0x000b,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_14},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_15},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_16},
    {.uuid=0x000b,.permissions=0x804,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_17},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_18},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_19},
    {.uuid=0x000e,.permissions=0x801,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_20},
    {.uuid=0x0000,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_21},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_22},
    {.uuid=0x8001,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_23},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x03,.clientconfig_index=0x00}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_25},
    {.uuid=0x8002,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_26},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x04,.clientconfig_index=0x01}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_28},
    {.uuid=0x8003,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_29},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x05,.clientconfig_index=0x02}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_31},
    {.uuid=0x8004,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_32},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x06,.clientconfig_index=0x03}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_34},
    {.uuid=0x8005,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_35},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x07,.clientconfig_index=0x04}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_37},
    {.uuid=0x8006,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_38},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x08,.clientconfig_index=0x05}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_40},
    {.uuid=0x8007,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_41},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x09,.clientconfig_index=0x06}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_43},
    {.uuid=0x8008,.permissions=0x803,.datatype=0x01,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_44},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x02,.index=0x0a,.clientconfig_index=0x07}},
    {.uuid=0x0002,.permissions=0x801,.datatype=0x00,.min_key_size=0x00,.constdata=&bg_gattdb_attribute_field_46},
    {.uuid=0x8009,.permissions=0x803,.datatype=0x02,.min_key_size=0x00,.dynamicdata=&bg_gattdb_attribute_field_47},
    {.uuid=0x000f,.permissions=0x807,.datatype=0x03,.min_key_size=0x00,.configdata={.flags=0x01,.index=0x0b,.clientconfig_index=0x08}},
};

GATT_DATA(const uint16_t bg_gattdb_attributes_dynamic_mapping_map[])={
	0x000f,
	0x0012,
	0x0015,
	0x0018,
	0x001b,
	0x001e,
	0x0021,
	0x0024,
	0x0027,
	0x002a,
	0x002d,
	0x0030,
};

GATT_DATA(const uint8_t bg_gattdb_adv_uuid16_map[])={0x03, 0x18, 0x02, 0x18, 0x04, 0x18, };
GATT_DATA(const uint8_t bg_gattdb_adv_uuid128_map[])={0x0f, 0x40, 0x7f, 0x5c, 0x7a, 0x2e, 0x41, 0xa7, 0x5a, 0x4f, 0xa9, 0x51, 0x65, 0xff, 0xc7, 0x6c, };
GATT_HEADER(const struct bg_gattdb_def bg_gattdb_data )={
    .attributes=bg_gattdb_attributes_map,
    .attributes_max=49,
    .uuidtable_16_size=16,
    .uuidtable_16=bg_gattdb_uuidtable_16_map,
    .uuidtable_128_size=10,
    .uuidtable_128=bg_gattdb_uuidtable_128_map,
    .attributes_dynamic_max=12,
    .attributes_dynamic_mapping=bg_gattdb_attributes_dynamic_mapping_map,
    .adv_uuid16=bg_gattdb_adv_uuid16_map,
    .adv_uuid16_num=3,
    .adv_uuid128=bg_gattdb_adv_uuid128_map,
    .adv_uuid128_num=1,
};

const struct bg_gattdb_def *bg_gattdb=&bg_gattdb_data;
