/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef BG_GATTDB_H
#define BG_GATTDB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define xgatt_lloss                            15
#define xgatt_alert                            18
#define xgatt_txpower                          21
#define button1                                24
#define button2                                27
#define button3                                30
#define button4                                33
#define button5                                36
#define button6                                39
#define button7                                42
#define button8                                45
#define gattSliderPacket                       48

#endif
